---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-eastus1-dev-2048-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: webapp-eastus1-dev-2048-game-conatiner
          image: 127355576263.dkr.ecr.us-east-1.amazonaws.com/ecr-eastus1-dev-salesforce:8a054da5380cd4f5ca2ed606cc4cc86fd2d93665
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: service-eastus1-dev-2048-game
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
